version: "3.9"
services:

  app:
    build: .
    container_name: afro-api
    ports:
      - "8000:8000"
    command: python /app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app  
    depends_on:
      - db
  db:
    image: postgres:latest
    hostname: postgres
    container_name: postgres_api
    ports:
      - "5432:5432"
    # volumes:
    #   - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=${DB_HOST}
      - "POSTGRES_HOST_AUTH_METHOD=trust"