version: "3.10"
services:

  app:
    build: 
      context: .
    container_name: afro-api
    ports:
      - "5000:5000"

    command: python manage.py runserver 0.0.0.0:5000
    volumes:
      - .:/app-server  
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=mongo
      - MONGO_INITDB_USERNAME=user
      - MONGO_INITDB_PASSWORD=pass
    hostname: mongodb
    ports:
      - "27017:27017"
