# Generated by Django 2.2.28 on 2024-02-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afroquotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='NiaBee', max_length=20),
        ),
    ]
