# Generated by Django 2.2.28 on 2023-12-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afroquotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='Chuma8', max_length=20),
        ),
    ]
