# Generated by Django 3.1.5 on 2021-03-04 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afroquotes', '0003_quote_timestamp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Anotation',
            new_name='Annotation',
        ),
        migrations.RenameField(
            model_name='annotation',
            old_name='anotated',
            new_name='annotated',
        ),
        migrations.RenameField(
            model_name='annotation',
            old_name='anotation',
            new_name='annotation',
        ),
        migrations.RenameField(
            model_name='annotation',
            old_name='anotator',
            new_name='annotator',
        ),
    ]
