# Generated by Django 4.0.2 on 2022-02-10 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afroquotes', '0005_annotation_timestamp_annotation_verified_upvote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='annotation_view_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='last_viewed',
            field=models.DateTimeField(null=True),
        ),
    ]
