# Generated by Django 4.0.2 on 2022-10-23 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afroquotes', '0006_annotation_annotation_view_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='approvers',
            field=models.ManyToManyField(related_name='approvers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='suggestioncomment',
            name='annotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='afroquotes.annotation'),
        ),
    ]
